create table
  public.global_inventory (
    id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    num_green_potions integer null,
    num_green_ml integer null,
    gold integer null,
    num_red_potions integer null,
    num_red_ml integer null,
    num_blue_potions integer null,
    num_blue_ml integer null,
    num_dark_ml integer null,
    num_dark_potions integer null,
    constraint global_inventorty_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potions (
    id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    sku text null,
    name text null,
    price integer null,
    inventory integer null,
    type integer[] null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts (
    id integer generated by default as identity,
    customer_name text null,
    character_class text null,
    level integer null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_items (
    id integer generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id integer null,
    potion_sku integer null,
    quantity integer null,
    constraint cart_items_pkey primary key (id)
  ) tablespace pg_default;